name: Postman API Tests

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:

  newman-tests:

    runs-on: windows-latest

    steps:

      # 1 - Clone repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2 - Install Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      # 3 - Verify versions
      - name: Verify Node and npm
        run: |
          node -v
          npm -v

      # 4 - Install Newman
      - name: Install Newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      # 5 - Create reports folder
      - name: Create Reports Folder
        run: mkdir reports

      # 6 - Run Newman collection
      - name: Run Postman Collection
        run: |
          newman run collections/CollectionClient2.postman_collection.json `
          -e environments/PP.postman_environment.json `
          -r cli,htmlextra `
          --reporter-htmlextra-export reports/report.html
        shell: powershell

      # 7 - Verify report
      - name: Verify HTML Report
        run: |
          if (Test-Path "reports/report.html") {
            Write-Host "Report generated successfully"
          } else {
            Write-Error "Report not found"
            exit 1
          }
        shell: powershell

      # 8 - Upload report artifact
      - name: Upload HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: newman-html-report
          path: reports/report.html

      # 9 - Send Email
      - name: Send Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587

          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}

          subject: GitHub Actions - Newman Report

          to: yanisall1012@gmail.com
          from: GitHub Actions

          body: |
            Bonjour,

            Les tests Postman ont été exécutés avec succès.

            Repository:
            ${{ github.repository }}

            Workflow:
            ${{ github.workflow }}

            Build:
            ${{ github.run_number }}

            Le rapport HTML est en pièce jointe.

          attachments: reports/report.html