name: Postman API Tests

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  newman-tests:
    runs-on: windows-latest

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Newman
        shell: pwsh
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Create reports folder
        shell: pwsh
        run: New-Item -ItemType Directory -Force reports

      - name: Run Postman Collection
        shell: pwsh
        run: |
          newman run "collections/CollectionClient2.postman_collection.json" `
            -e "environments/PP.postman_environment.json" `
            -r cli,htmlextra `
            --reporter-htmlextra-export "reports/report.html"

      - name: Verify report exists
        shell: pwsh
        run: |
          Get-ChildItem -Recurse reports

      - name: Upload HTML Report (backup)
        uses: actions/upload-artifact@v4
        with:
          name: newman-report
          path: reports/report.html

      - name: Send Email with HTML Report
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          secure: false

          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}

          subject: GitHub Actions - Newman HTML Report

          to: yanisall1012@gmail.com
          from: GitHub Actions

          body: |
            Les tests Postman sont terminés.

            Repository :
            https://github.com/yanisall1012/postman-api-test

            📊 Rapport HTML joint à cet email.

          attachments: ./reports/report.html